#!/usr/bin/env bash

# add following lines to ~/.bashrc:
# if [ -f ~/bin/aliases ]; then
#     . ~/bin/aliases
# fi

# Autocompletion
if [ -f ~/bin/.autocomplete.sh ]; then
    . ~/bin/.autocomplete.sh
fi

PATH=$PATH:~/bin:~/bin/bin:~/.local/bin:~/private-scripts/bin:~/winhome/scripts

#set -o vi
bind -m vi-insert "\C-l":clear-screen
# ctrl-space is bind <leader> for now

# == Small bind docs:
# - bind -S: see binds
# - bind -P: see commands (bound and not)

# bind '"\C- f":"$(fzf --height 15)"'
# bind '"\C- v":"vim $(fzf --height 15)"'

# bind '"\C-n":"tree"'
navigate_dir_fzf () {
    TARGET=$(fd --type d | fzf --height 30)
    [[ -z "$TARGET" ]] && return
    cd $TARGET
}
# bind '"\C-j":"navigate_dir_fzf"'

# left alt bindings
# bind '"x":" | xargs -I@ "'
# bind '"g":" | grep "'
# bind '"v":" | vim -"'
# bind '"d":"$(date -u +\"%Y-%m-%d\")"'
# bind '"s":" | clip"'
# bind '"f":"vim $(find | fzf --height 15)"'

# bind ctrl-k to exa or ls -l
if command -v exa &> /dev/null
then
#    bind '"\C-k":"exa -a"'
    alias ll='exa -alFh'
    alias la='exa -ah'
    alias lt='exa --sort oldest'
    alias l='exa -Fh'
    alias lf='exa -th | head -1'
else
#    bind '"\C-k":"ls -a"'
    alias ll='ls -alFh'
    alias la='ls -Ah'
    alias lt='ls -th'
    alias l='ls -CFh'
    alias lf='ls -th | head -1'
fi

if command -v batcat &> /dev/null
then
    alias cat='batcat --plain --wrap character'
fi

alias mv='mv -i'
alias cp='cp -i'

alias pgrep='pgrep -f -l'
alias pkill='pkill -s 9 -f'
alias ps='ps aux'

alias ai='sudo apt install'
alias au='sudo apt update'
alias aug='sudo apt upgrade'
alias ar='sudo apt remove'
alias aar='sudo apt autoremove'

al () {
    apt list "*$1*"
}
ali () {
    apt list --installed "*$1*"
}

alias ase='apt search'
alias ash='apt show' # apt show pckgname - shows information about a package
alias av='apt-cache policy'

alias ni='npm install'
alias nig='npm install --global'
alias nis='npm install --save'
alias nisd='npm install --save-dev'
alias nid='npm install --save-dev'
alias nrm='npm remove'
alias nrmg='npm remove --global'
alias ns='npm start'
# alias nr='npm run'
nr () {
    if [ $# -eq 0 ]; then
        [ ! -f package.json ] && echo no package.json in current dir && return
        mkdir -p /home/$USER/.local/nr
        CACHEFILE="/home/$USER/.local/nr/$(basename $PWD)"
        CACHEHASHFILE="/home/$USER/.local/nr/$(basename $PWD)_hash"

        HASH=$(sha1sum package.json | awk '{print $1}')
        CACHEHASH=$(cat $CACHEHASHFILE 2> /dev/null)

        if [[ $HASH == $CACHEHASH ]]
        then
            echo package.json has not changed, using cache
            ID=$(cat $CACHEFILE | fzf --tac)
        else
            echo package.json has changed
            echo $HASH > $CACHEHASHFILE
            cmd.exe /c npm run > $CACHEFILE
            ID=$(cat $CACHEFILE | fzf --tac)
        fi

        history -s npm run $ID
        echo $PWD npm run $ID >> ~/.persistent_history
        cmd.exe /c npm run $ID
    else
        history -s npm run $1
        echo $PWD npm run $1 >> ~/.persistent_history
        cmd.exe /c npm run $1
    fi
}
alias nre='npm run env'

alias df='df -Th'
alias writer='lowriter'
alias work='cd ~/winhome/work'
alias components='cd ~/winhome/source/components'
alias notes='cd ~/notes'
alias todo='start https://docs.google.com/document/d/153zkJW6oph4Av4q495SS5dufi3Z5L79GP6koM0jKI1w/edit#'

# platform specific stuff
if [[ "$(uname)" == "Darwin" ]]; then # It's a Mac!
    echo mac
    alias dl='cd ~/Downloads'
    alias desk='cd ~/Desktop'
    alias xc='pbcopy'
    alias xpaste='pbpaste'
    export DL=~/Downloads
    export DESK=~/Desktop
elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then # It's Good ol' Linux or WSL!
    if [ $(uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/ip') ];
    then # WSL
        # if not done, create symlink in ~ pointing to windows user home called 'winhome'
        copy_ip () {
            hostname -I | awk '{print $1}' | awk '{printf "%s", $0}' | clip.exe
        }
        alias cmd='cmd.exe'
        alias open='cmd.exe /C start'
        alias o='cmd.exe /C start'
        alias start='cmd.exe /C start'
        alias clip='clip.exe'
        alias winhome='cd ~/winhome'
        alias wh='cd ~/winhome'
        alias xc='clip.exe'
        alias dl='cd ~/winhome/Downloads'
        alias desk='cd ~/winhome/Desktop'
        alias osite="egrep -o 'https?://[^ ]+'| tr -d '' | xargs cmd.exe /C start" # opens siteurl from std/in
        alias gitg='cmd.exe /C "C:\Program Files\gitg\bin\gitg.exe"' # opens gitgui in current dir
        alias cset='cmd.exe /C set'
        alias csetx='cmd.exe /C setx'
        # alias node='cmd.exe /c node'
        #alias npm='cmd.exe /c npm'
        alias npx='cmd.exe /c npx'
        alias dotnet='cmd.exe /c dotnet'
        alias gradlew='cmd.exe /c gradlew'
        alias func='func.exe'
        alias es='cmd.exe /c es'
        rider () {
            cmd.exe /c 'C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\"Start Menu"\Programs\"JetBrains Toolbox"\Rider.lnk' . &
        }
        webstorm () {
            cmd.exe /c 'C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\"Start Menu"\Programs\"JetBrains Toolbox"\Webstorm.lnk' . &
        }
        pycharm () {
            cmd.exe /c 'C:\Users\%USERNAME%\scripts\pycharm_link.bat' $(cmd.exe /c echo '%cd%') &
            # pycharm_link.bat: C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\"Start Menu"\Programs\"JetBrains Toolbox"\"PyCharm Professional.lnk" %1
        }
        intellij () {
            cmd.exe /c 'C:\Users\%USERNAME%\scripts\intellij_link.bat' $(cmd.exe /c echo '%cd%') &
            # intellij_link.bat: C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\"Start Menu"\Programs\"JetBrains Toolbox"\"IntelliJ IDEA Ultimate.lnk" %1
        }
        delenv () {
            if [ $# -eq 0 ]
            then
                ARG=$(cmd /c set | fzf | awk -F '=' '{print $1}')
            else
                ARG="$1"
            fi
            # cmd.exe /C "REG delete HKCU\Environment /F /V $ARG"
            cmd.exe /C setx $ARG ""
            echo "Removing $ARG. If success, remember to restart entire terminal."
        }
        alias regdel='delenv'
        alias delreg='delenv'
        export WH=~/winhome
        export DL=~/winhome/Downloads
        export DESK=~/winhome/Desktop

        winpath () {
            cmd.exe /c path | sed 's/;/\n/g' | fzf
        }
        winpwd () {
            cmd.exe /c echo %cd%
        }
        winxp () { # Copy windows path of dir/file
            if [ -z "$1" ]; then
                P=$(realpath .)
            else
                P=$(realpath $1)
            fi
            P=$(echo $P | sed -e 's/\//\\/g' | sed -e 's/\\mnt\\c/C:/')
            echo "copied $P"
            echo -n $P | clip.exe
        }
        alias pc="winxp"
        # alias curl='cmd.exe /c curl' # use cmd curl in wsl because of localhost problems
    else # It actually is linux
        alias dl='cd ~/Downloads'
        alias desk='cd ~/Desktop'
        alias xc='xclip -selection c' # example: pwd | xc
        alias clip='xclip -selection c' # example: pwd | xc
        alias open='xdg-open'
        alias xpaste='xclip -selection clipboard -o'
        export DL=~/Downloads
        export DESK=~/Desktop
    fi
fi

# misc stuff
alias cmux='sudo chmod u+x'
alias rsync='rsync -arvzP'
alias drivemount='google-drive-ocamlfuse' # first arg: mountdir
alias unmount='fusermount -u' # first arg: mountdir
alias rb='. ~/.bashrc'
alias rbc='. ~/.bashrc'
alias breset='. ~/.bashrc'
alias sourcebrc='. ~/.bashrc'
alias vact='. $(pwd)/venv/bin/activate'
alias tarzip='tar -cvf' # args: TARNAME FILES
alias tarunzip='tar -xvf' # args: TARNAME

wordcount () {
    echo $1 | wc --words -
}
trspace () {
    echo "$@" | tr " " "_"
}
arrayify () {
    echo "[$@]" | tr "\n" ", " # cut off last two chars at some point
}
trupper () {
    echo "$@" | tr '[:lower:]' '[:upper:]'
}
trlower () {
    echo "$@" | tr '[:upper:]' '[:lower:]'
}

trim() {
    #local var="$*"
    read var # from pipe
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    echo -n "$var"
}


sgrep () {
    grep -irn "$1" .
}
greps () {
    grep -irn "$1" .
}

xp () {
    if [ $# -eq 0 ]
    then
        realpath . | tr -d "\n" | xc
    else
        realpath $1 | tr -d "\n" | xc
    fi
}


cac () {
    cat $1 | xc
}

alias linuxv='cat /etc/*-release'

#navigation aliases
alias ca='cd ..'
alias caa='cd ../..'
alias caaa='cd ../../..'
alias caaaa='cd ../../../..'
alias caaaaa='cd ../../../../..'
alias caaaaaa='cd ../../../../../..'
alias caaaaaaa='cd ../../../../../../..'
alias caaaaaaaa='cd ../../../../../../../..'
alias caaaaaaaaa='cd ../../../../../../../../..'
alias caaaaaaaaaa='cd ../../../../../../../../../..'
alias caaaaaaaaaaa='cd ../../../../../../../../../../..'
alias cb='cd -'

#alias cdf='cd $(ls -d ./*/ | head -1)' # enter first dir
#alias cdl='cd $(ls -dr ./*/ | head -1)' # enter last dir
alias cdl='cd $(ls -t | head -1)'

alias bin='cd ~/bin'
alias www='cd /var/www/html/'

#search aliases
# trying out https://github.com/sharkdp/fd for now
# findall () {
#     find . -iname "*$1*"
# }
# fd () {
#     find . -type d -iname "*$1*"
# }
alias fda='fd --hidden'
alias fdf='fd | fzf'

cdd() { # try to cd to a dir match
    DIRS=$(find . -type d -iname "*$1*")
    NUM=$(echo -n "$DIRS" | grep -c '^')
    if [ $NUM -eq 0 ]; then
        echo did not match any dirs
    elif [ $NUM -eq 1 ]; then
        cd $DIRS
    else
        echo Matched more than one dir:
        for dir in $DIRS
        do
            echo $dir
        done
    fi
}
alias cfd='cdd'
finddir () {
    find . -type d -iname "*$1*"
}

ff () {
    find . -type f -iname "*$1*"
    #rg --hidden --files -g "*$1*"
}
findfile () {
    find . -type f -iname "*$1*"
    #rg --hidden --files -g "*$1*"
}
ffreg () {
    if [ $# -eq 0 ]
    then
        echo 'regex find from current dir. input1 must be in quotation and you need to specify .*/ in the beginning because find matches the whole path. eg to find all files ending with .log: ".*\.log$"'
    else
        find . -regextype sed -regex $1
    fi
}
findlib () {
    if [ $# -eq 0 ]
    then
        ldconfig -p
    else
        ldconfig -p | grep -i $1
    fi
}
# can also use locate PATTERN to find a file on the system (much faster)
findcore () { # search EVERYWHERE # can also use locate for this
    sudo find /bin /lib /lib64 /snap /usr /etc /opt /sbin /var /home -iname "*$1*"
}

alias countfiles='find . -type f | wc -l'
alias countdirs='find . -maxdepth 1 -type d | wc -l'

# list, move, copy, open latest modified file / dir in current dir
lst() {
    if [ $# -eq 0 ]
    then
        ls -t | head -1
    else
        ls -t | head -$1
    fi
}
vlst() {
    vim $(lst)
}
alias vimlst='vlst'
mvl () {
    if [ $# -eq 1 ]
    then
        mv -i -v $(lst) $1
    else
        mv -i -v $(lst $1) $2
    fi
}
cpl () {
    if [ $# -eq 1 ]
    then
        cp -ir $(lst) $1
    else
        cp -ir $(lst $1) $2
    fi
}
ol () {
    open $(lst)
}

alias fori="for ((I=0;;I++)) do"

#====== Vim stuff
# wrapper for vim that allows to use previously captured keys by terminal like c-s for mappings
vim () {
    stty -ixon;
    command vim "$@";
    stty ixon;
}
vi () {
    stty -ixon;
    command vim "$@";
    stty ixon;
}

export VISUAL=vim
export EDITOR="$VISUAL"
alias evim="vim ~/.vimrc"
alias evimrc="vim ~/.vimrc"
alias viml="vim $(lst)"

ffv () {
    vim $(rg -i --hidden --files -g "*$1*")
}
ffrm () {
    rm $(rg -i --hidden --files -g "*$1*")
}
rgvim () {
    rg -i --vimgrep --hidden "$1" > ~/.local/vim_quickfix_list
    vim -q ~/.local/vim_quickfix_list
    rm ~/.local/vim_quickfix_list
}
alias rgv='rgvim'

# read about navigation via quickfix with 'docs vim'

# quickly search aliases
als () {
    if [ $# -eq 0 ]
    then
        cat ~/bin/aliases
    else
        cat ~/bin/aliases | grep -i "$@"
    fi
}
if [ -f ~/bin/git_aliases ]; then
    . ~/bin/git_aliases
    alias egitals='vim ~/bin/git_aliases'

    gitals () {
        if [ $# -eq 0 ]
        then
            cat ~/bin/git_aliases
        else
            cat ~/bin/git_aliases | grep -i $1
        fi
    }
fi
if [ -f ~/bin/azure/aliases ]; then
    . ~/bin/azure/aliases
    alias eaz='vim ~/bin/azure/aliases'
fi

# drive aliases
alias eals='vim ~/bin/aliases'
alias ebrc='vim ~/.bashrc'
alias ezrc='vim ~/.zshrc'


dragon-say () {
echo $1 | cowsay -e OO -f dragon-and-cow
}


#shopt -s globstar

#fasd init. Try different setups from "man fasd"
# eval "$(fasd --init auto)"
# alias v='f -e vim' # quick opening files with vim
# c () {
#     echo "copied $(f $@) to clipholder"
#     f -e cat $@ | tr -d '\n' | xc
# }
# o () {
#     echo "opening $(f $@)"
#     f -e open $@ & disown
# }

# bin search
rgb () {
    rg -i "$@" ~/bin
}
alias bs="rgb"


# documents
alias books='open https://docs.google.com/document/d/1Kz8ryAhjm8AHjcVO956MMFzlwhvrF84n0x21UVvmjA0/edit'
alias activities='open https://docs.google.com/document/d/1mKbc0Or2XXEoOD5FeBMuv4sDaxz_Gfh8pwBtoabJrfU/edit'
alias career='open https://docs.google.com/document/d/191BaYenDZRrsV5F8JS0t0LbSyWddEC1dGhrqj7DGfkk/edit'
alias friends='open https://docs.google.com/document/d/1MwawZDJWUjvCwoLIukIJlS-L3Czc9gCQTti04PZSLII/edit'
alias wishlist='open https://docs.google.com/document/d/1GapiFZZXzOXmDn1hb6Uy4f_jUxMTnPr3b2jAlHL06ag/edit'
alias hours='open https://docs.google.com/spreadsheets/d/1Z-3PQJbS1fUwjIs86l6sh5ffAfT7gtQz6pg7tfYzE2I/edit'

# cat ssh config
alias sshconf='cat ~/.ssh/config'
alias sshc='sshconf'
alias esshconf='vim ~/.ssh/config'
alias esshc='esshconf'
alias sshkeycopy='cat ~/.ssh/id_rsa.pub | clip'
alias sshcopy='sshkeycopy'

# shell timers
countdown(){
    date1=$((`date +%s` + $1));
    while [ "$date1" -ge `date +%s` ]; do
        echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
        sleep 0.1
    done
}
stopwatch(){
    date1=`date +%s`;
    while true; do
        echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
        sleep 0.1
    done
}
alarm(){
    countdown $1 && open ~/bin/bin/alarm.wav
}

# google search for string
gsearch() {
    if [ $# -eq 0 ]
    then
        echo "first arg must be search string"
    else
        google-chrome "https://www.google.com/search?q=$(echo $1 | tr ' ' '+')"
    fi
}

# start static file httpserver in current dir. Arg1: port
simpleserver(){
    python3 -m http.server $1
}
httpserver(){
    python3 -m http.server $1
}

uuid() {
    python3 -c 'import uuid; print(str(uuid.uuid4()))'
}
guid() {
    python3 -c 'import uuid; print(str(uuid.uuid4()))'
}

# replace space in file names with underscore
rename_space_underscore() {
    for arg in "$@"
    do
        mv "$arg" $(echo $arg | tr " " "_")
        echo $arg renamed to: $(echo $arg | tr " " "_")
    done
}

# replace space with underscore normal input
tr_underscore(){
    echo "$@" | tr " " "_"
}

alias scanlocal='sudo nmap -sn 192.168.87.0/24'

viewlog() {
    less +F ~/logs/$1
}

# Print Len of input
strlen() {
    strlenargs="$@"
    echo ${#strlenargs}
}

alias rg='rg -i -M 400'
alias less='less +F' # real time update on file

# history
alias ghist='cat ~/.bash_history | grep'
alias ehist='vim ~/.bash_history'

# zsh shell aliases
alias d='dirs -v | head -10'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
# alias -g G='| grep -i' # Bash can't handle this


# === docker
if [ -f ~/bin/docker/docker-aliases.sh ]; then
    . ~/bin/docker/docker-aliases.sh
fi


# cat ide search replace patterns
alias idesrp="cat ~/bin/ide-config/jetbrains/search-replace-patterns"

alias jvu="sudo update-alternatives --config java"
alias jvm="sudo update-alternatives --config java"
alias javav="sudo update-alternatives --config java"

# find files in parent dirs
find-up () {
  path=$(pwd)
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  echo "$path"
}
egiti() {
    path="$(find-up .gitignore)/.gitignore"
    vim $path
}
alias giti='egiti'

alias dclean='dotnet clean'
alias drun='dotnet run'


# autohotkey
ahk () { # edit and launch autohotkey script
    AHK_FILE_DIR=~/winhome/autohotkey
    if [ -z "$1" ]; then
        echo "First arg should be name of autohotkey script that should be executed (tab for completion, remember .ahk ending)"
        echo "If first arg is -e flag: edit file instead"
        echo "If first arg is -s flag: open WindowSpy"
        echo "Files end up in $AHK_FILE_DIR dir"
        return
    fi

    if [ "$1" == "-s" ]; then
        cmd /c "C:\Program Files\AutoHotkey\WindowSpy.ahk" &
        return
    fi

    # create / edit script if -e flag
    if [ "$1" == "-e" ]; then
        shift
        mkdir -p $AHK_FILE_DIR
        # if file does not exist, create from template
        [ ! -f $AHK_FILE_DIR/$1 ] && echo "Creating new file from template" && cp ~/bin/autohotkey/template.ahk $AHK_FILE_DIR/$1
        vim $AHK_FILE_DIR/$1
        return
    fi

    # execute script
    cmd /c autohotkey.exe %USERPROFILE%\\autohotkey\\$1 & # does not seem to quit if terminal is shut down
}

# === persistent history, credits to https://eli.thegreenplace.net/2013/06/11/keeping-persistent-history-in-bash
# export HISTTIMEFORMAT="%F %T  " # changes history format to include datetime ## messes with new sysz
do_not_persist_array=("ls" "la" "bin" "gp" "gst" "gaa" "gd" "gb" "eals" "rbc" "gl" "zz" "ca" "cb")
log_bash_persistent_history()
{
  [[
    $(history 1) =~ ^\ *[0-9]+\ +(.*)$
  ]]
  local command_part="${BASH_REMATCH[1]}"
  if [ "$command_part" != "$PERSISTENT_HISTORY_LAST" ]
  then
      # Don't persist very common commands
      for substring in "${do_not_persist_array[@]}"; do
          if [[ "$command_part" == "$substring" ]]; then
              return
          fi
      done
      echo "$PWD $command_part" >> ~/.persistent_history
      export PERSISTENT_HISTORY_LAST="$command_part"
  fi
}

# Stuff to do on PROMPT_COMMAND
run_on_prompt_command()
{
    log_bash_persistent_history
}

PROMPT_COMMAND="run_on_prompt_command"

# keybinding to search in persistent history
__fzf_persistent_history__() {
  local output
  # removes first line which is now path command was called from
  output=$(tac ~/.persistent_history | sed 's/[^ ]* *//' | fzf --no-sort)
  # below put output on prompt
  READLINE_LINE=${output#*$'\t'}
  if [ -z "$READLINE_POINT" ]; then
    echo "$READLINE_LINE"
  else
    READLINE_POINT=0x7fffffff
  fi
}
bind -m emacs-standard -x '"\C-p": __fzf_persistent_history__'

# keybinding to search in persistent history in current dir
__fzf_persistent_history_in_dir__() {
  local output
  # maybe futurework: filter by current dir, then by parent dir, then by child dirs
  # echo $PWD
  output=$(tac ~/.persistent_history | grep "^$PWD " | sed 's/[^ ]* *//' | fzf --no-sort)
  # echo $output
  # below put output on prompt
  READLINE_LINE=${output#*$'\t'}
  if [ -z "$READLINE_POINT" ]; then
    echo "$READLINE_LINE"
  else
    READLINE_POINT=0x7fffffff
  fi
}
bind -m emacs-standard -x '"\C-O": __fzf_persistent_history_in_dir__'
# bind -m emacs-standard -x '"": __fzf_persistent_history_in_dir__'

# register hook that saves last pwd to cachefile
settitle () {
  export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
  echo -ne '\033]0;'"$1"'\a'
}
LASTPWD=~/.cache/last-pwd.txt
typeset -g CHPWD_COMMAND=""
_chpwd_hook() {
  echo "$PWD" > "$LASTPWD"
  settitle "$PWD"
}
PROMPT_COMMAND="_chpwd_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"

# start at last dir
if [ -f $LASTPWD ]; then
    cd $(cat "$LASTPWD")
fi

alias isodate='date -u +"%Y-%m-%dT%H:%M:%S%Z"'

mockpile() {
    powershell.exe -command "Get-Clipboard" > ~/winhome/.cache/mockpileinput.json
    # cat ~/winhome/.cache/mockpileinput.json
    # ~/winhome/scripts/mockpilercli.exe /home/marand/winhome/.cache/mockpileinput.json
    # cmd.exe /C echo %HOMEPATH%
    ~/winhome/scripts/mockpilercli.exe "C:\\Users\\Martin\\.cache\\mockpileinput.json"
}

sqlite_from_json() {
    if [ -z "$1" ]; then
        echo taking json from clipboard
        powershell.exe -command "Get-Clipboard" > ~/winhome/.cache/sqlite_json.json
    else
        echo copy from file
        cp -f $1 ~/winhome/.cache/sqlite_json.json
    fi

    cd ~/winhome/.cache
    echo === starting sqlitebiter jsonparse
    cmd /c sqlitebiter file sqlite_json.json
    echo === sqlitebiter jsonparse done
    cmd /c "C:\\Users\\mar\\AppData\\Local\\JetBrains\\Toolbox\\apps\\Rider\\ch-0\\213.6461.51\\bin\\rider" out.sqlite
    cd -
}
sqlite_from_sql() {
    powershell.exe -command "Get-Clipboard" > ~/winhome/.cache/sqlite_from_sql_cache.sql
    if [ -f ~/winhome/.cache/temp.db ]; then
        rm ~/winhome/.cache/temp.db
    fi
    sqlite ~/winhome/.cache/temp.db < ~/winhome/.cache/sqlite_from_sql_cache.sql
    cd ~/winhome/.cache
    cmd /c rider temp.db
    cd -
}

# list processes and kill one
pskill() {
    P_TO_KILL=$(cmd /c pslist | fzf | awk '{print $1}')
    [ -z "$P_TO_KILL" ] && return
    ALL_P_PID=$(cmd /c pslist | grep -i "$P_TO_KILL" | awk '{print $2}')
    for PID in $ALL_P_PID; do
        cmd /c pskill $PID
    done
}
alias pk='pskill'
alias pkill='pskill'
alias psk='pskill'

alias sysvar='cmd /c rundll32 sysdm.cpl,EditEnvironmentVariables'
alias path='cmd /c rundll32 sysdm.cpl,EditEnvironmentVariables'
alias epath='cmd /c rundll32 sysdm.cpl,EditEnvironmentVariables'
alias setpath='cmd /c rundll32 sysdm.cpl,EditEnvironmentVariables'

alias setf='cmd /c set | fzf'

# quick z navigation
zz () {
    # z binary from https://github.com/rupa/z must be in path and should be sourced from bashrc
    if [ "$#" -gt 0 ]; then
        TO_PATH=$(z | awk '{print $2}' | tac | fzf --height 30 --query "$@")
    else
        TO_PATH=$(z | awk '{print $2}' | tac | fzf --height 30)
    fi

    # if not empty, go to path
    if [ ! -z "$TO_PATH" ]; then
        cd $TO_PATH
    fi
}

watch() {
    if [ -z "$1" ]; then
        tldr watchexec
        echo ""
        echo "watchexec -r -e py -- python server.py        Call/restart python server.py when any Python file in the current directory (and all subdirectories) changes"
        echo "watchexec -r -- 'echo \$WATCHEXEC_COMMON_PATH/\$WATCHEXEC_WRITTEN_PATH | wc -c'    pipe modified / created filenames"
        echo "watchexec  -r  -- 'realpath --relative-to=. \$WATCHEXEC_COMMON_PATH/\$WATCHEXEC_WRITTEN_PATH'         get path of new / modified files relative to current dir"
        echo "watchexec --print-events ...      print events that watchexec see"
        echo "For more examples: https://github.com/watchexec/watchexec/tree/main/cli#usage-examples"
        return
    fi
    if $(pwd -P | grep -q "^\/mnt\/c\/*"); then
        cmd /c watchexec "$@"
    else
        if ! command -v watchexec &> /dev/null
        then
            echo "watchexec could not be found"
            echo "install with 'wget https://github.com/watchexec/watchexec/releases/download/cli-v1.19.0/watchexec-1.19.0-x86_64-unknown-linux-musl.deb && sudo dpkg -i watchexec-1.19.0-x86_64-unknown-linux-gnu.deb'"
        else
            watchexec "$@"
        fi
    fi
}
pywatch() {
    if [ -z "$1" ]; then
        echo "first arg must be python file followed by optional args"
        return
    fi
    watch  -c -- python "$@"
}
nodewatch() {
    if [ -z "$1" ]; then
        echo "first arg must be node file followed by optional args"
        return
    fi
    watch  -c -- node "$@"
}

# apt install trash-cli. trash ends up in ~/.local/share/Trash/. use trash-list to list. trash-restore to restore.
rm() {
    trash "$@"
}

docs() {
    DOC=$(ls ~/bin/documentation | sort | uniq | fzf --preview='less ~/bin/documentation/{}' --bind shift-up:preview-page-up,shift-down:preview-page-down)
    vim ~/bin/documentation/$DOC
}
docssearch() {
    if [ -z "$1" ]; then
        "first arg to docssearch should be search rg term"
        return
    fi
    rg "$@" ~/bin/documentation
}
alias ds="docssearch"

alias plist="tasklist.exe"
alias tf="terraform.exe"

# java version manager :P
alias jvm="sudo update-alternatives --config java"

# lightblue colors for dirs, which removes annoying background in windows part of fs
# run: dircolors -p | sed 's/;42/;01/' > ~/.dircolors
#LS_COLORS=$LS_COLORS:'di=1;34:' ; export LS_COLORS

ideavim_actionlist() {
    cat ~/bin/datafiles/ideavim-actionlist.txt | fzf
}

alias dn="dotnet"
dnnew() {
    SELECTED=$(dotnet new --list | fzf)
    echo $SELECTED
}

# decode jwt and show payload. Credits: https://prefetch.net/blog/2020/07/14/decoding-json-web-tokens-jwts-from-the-linux-command-line/
jwtd() {
    if [ $# -eq 0 ]
    then
        powershell.exe -command "Get-Clipboard" > ~/winhome/.cache/jwtd_input.json
        OUT=$(cat ~/winhome/.cache/jwtd_input.json | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson')
        echo $OUT | jq
        EXP=$(echo $OUT | jq '.exp // empty')
        echo Expiry time: $(date -d @$EXP)
    else
        jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
    fi
}

# encode json from clipboard to base64 and open in jsonhero
jhero() {
    powershell.exe -command "Get-Clipboard" > ~/winhome/.cache/jsonhero_input.json
    start https://jsonhero.io/new?j=$(cat ~/winhome/.cache/jsonhero_input.json | base64 -w 0)
}

# to make use of https://github.com/MyrionSC/sysz-append-history
sysz() {
    history -w; history -c;
    eval $(which sysz) # for some reason just: sysz kills the shell
    history -r;
}

cdf () {
    cd $(find . -type d | fzf)
}

search_custom_commands () {
    compgen -A function -abk | fzf
}
search_all_commands () {
    compgen -A function -abck | fzf
}

alias untar='tar xvf'
alias te='cd $(tere)'
alias untar='tar xvf'

alias pathkill='findhandle'
alias killpath='findhandle'
alias findpath='findhandle'
alias handlefind='findhandle'

alias windir='cmd /c echo %cd%'
alias rp='realpath'

alias jobs='jobs && echo to kill job X: kill %X'

where () {
    if [ $# -eq 0 ]
    then
        echo first arg must be name of command
        return
    fi
    T=$(type "$1" | head -n 1)
    echo $T
    if [[ "$T" == *"is aliased to"* ]]; then
        rg "alias $1 ?=" ~/bin
        read -r -p "edit? [Y/n] " response
        if [[ "$response" =~ ([yY]|)$ ]]
        then
            rg --vimgrep --hidden "alias $1 ?=" ~/bin ~/.bashrc > ~/.local/vim_quickfix_list
            vim -q ~/.local/vim_quickfix_list
            rm ~/.local/vim_quickfix_list
        fi
    elif [[ "$T" == *"is a function"* ]]; then
        rg "$1 ?\(\) ?\{" ~/bin
        read -r -p "edit? [Y/n] " response
        echo $response
        if [[ "$response" =~ ([yY]|)$ ]]
        then
            rg --vimgrep --hidden "$1 ?\(\) ?\{" ~/bin ~/.bashrc > ~/.local/vim_quickfix_list
            vim -q ~/.local/vim_quickfix_list
            rm ~/.local/vim_quickfix_list
        fi
    elif [[ "$T" == *"is"* ]]; then
        echo "is file or link"
        read -r -p "edit? [Y/n] " response
        if [[ "$response" =~ ([yY]|)$ ]]
        then
            vim $(command -v $1)
        fi
    else
        return # prints "not found"
    fi
}
alias whe='where'

alias debinstall='sudo dpkg -i'
alias chx='chmod +x'

alias wt='wintools'

alias pers='cat ~/.persistent_history'


# === Airmaster
web() {
  cd ~/winhome/source/airmaster/airlinq-web
}
web_run() {
  cd ~/winhome/source/airmaster/airlinq-web
  npm run start_local
}
web_run_dev_local() {
  cd ~/winhome/source/airmaster/airlinq-web
  npm run start_dev_local
}
web_run_dev_local_api() {
  cd ~/winhome/source/airmaster/airlinq-web
  npm run start_dev_local_api
}
web_run_prod_local() {
  cd ~/winhome/source/airmaster/airlinq-web
  npm run start_prod_local
}
web_run_prod_local_api() {
  cd ~/winhome/source/airmaster/airlinq-web
  npm run start_prod_local_api
}
web_pipe() {
  start https://dev.azure.com/airmasteras/AirlinqOnline/_build?definitionId=2
}
api() {
  cd ~/winhome/source/airmaster/airlinq-api
}
api_run() {
  cd ~/winhome/source/airmaster/airlinq-api
  dotnet watch --project src/UI/InternalAPI/
}
api_run_dev() {
  cd ~/winhome/source/airmaster/airlinq-api
  dotnet watch run --project src/UI/InternalAPI/ --launch-profile InternalAPIDevelopment
}
api_run_prod() {
  cd ~/winhome/source/airmaster/airlinq-api
  dotnet watch run --project src/UI/InternalAPI/ --launch-profile InternalAPIProduction
}
api_health_prod() {
    curl --silent https://web-api.airlinq.eu/health | jq
}
api_health_test() {
    curl --silent https://api-web-test.airlinq.eu/health | jq
}
api_pipe() {
    start https://dev.azure.com/airmasteras/AirlinqOnline/_build?definitionId=9
}
api_swagger() {
    start https://api-web-test.airlinq.eu/swagger
}

alias jmeter='cmd.exe /c jmeter'
alias func='cmd.exe /c func.exe'

cos() {
    CMD=$(compgen -c cos_ | sort | uniq | fzf)
    history -s "$CMD | jless"
    echo "$PWD $CMD | jless" >> ~/.persistent_history
    bash $CMD | jless
}

utils() {
    UTIL=$(ls ~/bin/utils | sort | uniq | fzf --preview='less ~/bin/utils/{}' --bind shift-up:preview-page-up,shift-down:preview-page-down)
    cat ~/bin/utils/$UTIL
}

alias mvdl='mv -v $DL/$(ls -t $DL | head -1) .'
alias cpdl='cp -v $DL/$(ls -t $DL | head -1) .'

urlencode() {
    echo $1 | jq -sRr @uri | trim
}

qr() {
    # get from clipholder
    CLIP=$(powershell.exe -command "Get-Clipboard")
    echo showing qrcode for: $CLIP
    (cd ~/winhome/scripts && powershell.exe -File QRCodeURI.ps1 $CLIP)
}

