#!/usr/bin/python

# Serves index.html in current dir or dir structure if no index.html

import SimpleHTTPServer
import SocketServer
import sys

if len(sys.argv) == 2:
    PORT = int(sys.argv[1])
else:
    print("first arg should be the port that that simple server should run on")
    exit()

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
Handler.extensions_map.update({
    '.webapp': 'application/x-web-app-manifest+json',
});

httpd = SocketServer.TCPServer(("", PORT), Handler)

print("Serving at port " + PORT)
httpd.serve_forever()
