#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Argument 1 needs to be a git repo"
	echo ""
	echo "Following git repos are available:"
	echo "todo"
	echo "wi-crawler"
	echo "starcraft-judication"
	echo "ang2-ts-server"
	echo "scripts"
	echo "diceroller"
	echo "nih-status"
	echo "redrain"
	echo "Uni"
	echo "foundafunny"
        exit
fi

git clone git@github.com:MyrionSC/$1.git

