#!/usr/bin/env python

import os
import sys
import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-c", "--copy", action='store_true', help="copies output to clipholder")
parser.add_argument("input", type=str, nargs='+',
                    help="files to be shared")
args = parser.parse_args()

inputargs = args.input

try:
    res2 = subprocess.check_output(["ls"] + inputargs)
except subprocess.CalledProcessError:
    print("some files / dirs do not exist. Try again.")
    exit();

try:
    subprocess.check_output(["scp", "-r"] + inputargs + ["marand@marand.dk:/var/www/html/share"])
except subprocess.CalledProcessError:
    exit();

path = "marand.dk/share/"
print("share succesful. links:")
print("")

if len(inputargs) == 1:
    out = path + inputargs[0]
else:
    out = reduce(lambda x, y: path + x + "\n" + path + y, inputargs) # Haha
print(out)

# insert to clipholder
if args.copy:
    print("")
    print("Copied to clipholder")
    os.system("echo " + repr(out) + " | xc")





