#!/usr/bin/env bash

# get text from clipholder, send to server
COPY=$(powershell.exe -command "Get-Clipboard" | perl -p -e 's/\r\n$//')
curl -X POST "https://marand.dk/mockpiler/" -H "accept: text/plain" -d "$COPY"

