#!/usr/bin/env python3
import os
import sys

input = sys.argv[1]

bashcmd = "streamlink "

if input.startswith("https://www.twitch.tv/"):
    bashcmd += input 
else:
    bashcmd += "https://www.twitch.tv/" + input

bashcmd += " 720p"

print(bashcmd)

os.system(bashcmd + " &")
#> /dev/null 2>&1 


