#!/usr/bin/env bash

# Opens a html string from clipholder in browser
# if [ "$#" -ne 1 ]; then
#     echo "Tries to convert first html string found in clipholder to file"
#     echo "arg1 should be file suffix (eg. pdf)"
#     exit -1
# fi

# platform specific stuff
if [ "$(uname)" == "Darwin" ]; then # It's a Mac!
    echo "TODO"
elif [ "$(uname)" == "MSYS_NT-10.0-18362" ]; then # It's MSYS2!
    powershell -command "Get-Clipboard" > ~/.cache/tohtml.html
    start ~/.cache/tohtml.html
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then # It's Good ol' Linux!
    echo Not Implemented
    # xclip -selection clipboard -o > ~/.cache/clipboard.txt
    # grep -E -o '[A-Za-z0-9+\/]{70,}(={1,6})?' ~/.cache/clipboard.txt > ~/.cache/b64c-clean.txt
    # base64 -d ~/.cache/b64c-clean.txt > ~/.cache/b64c.$1
    # /usr/bin/xdg-open ~/.cache/b64c.$1
fi

