#!/usr/bin/env bash

# platform specific stuff
if [ "$(uname)" == "Darwin" ]; then # It's a Mac!
    xc='pbcopy'
elif [ "$(uname)" == "MSYS_NT-10.0-18362" ]; then # It's MSYS2!
    xc='clip'
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then # It's Good ol' Linux!
    xc='xclip -selection c' # example: pwd | xc
fi

if [ $# -eq 0 ]
then
    ls ~/bin/variables
else
    echo "copied $1 to clipholder"
    cat ~/bin/variables/$1 | $xc
fi

