#!/usr/bin/env bash

alias eazals='vim ~/bin/azure/aliases'

az_account_show() {
    az account show | jq .
}

az_account_list() {
    az account list | jq .
}

# subs
az_account_change_sub () {
    NAME=$(az account list | jq '.[].name' | fzf --height 15)
    SUB=$(az account list | jq ".[] | select(.name==$NAME)")
    az account set --subscription $(echo $SUB | jq .id | sed -e 's/^.//' -e 's/.$//')
    echo changed to subscription:
    echo $SUB | jq .
}

az_logstream() {
    az webapp log tail --resource-group RG --name WebAppName
}

az_tasks_create_story() {
    az boards work-item create \
        --title "$@" \
        --type "Product Backlog Item" \
        --fields "System.IterationId=211" "System.IterationLevel1=ProjName" "System.IterationLevel2=Sprint\ X" | tee ~/.cache/az_tasks_create
    NAME=$(cat ~/.cache/az_tasks_create | jq '.["fields"]["System.Title"]' | tr " " "-" | tr -d ":" | tr -d "\"")
    ID=$(cat ~/.cache/az_tasks_create | jq .id)
    git co -b "story/$ID-$NAME"
    cmd.exe /c start https://dev.azure.com/SUB/_workitems/edit/$ID
}

