#!/usr/bin/env python

import sys
import discord

if len(sys.argv) < 2:
    print("first arg must be message string")
    exit()

msg = sys.argv[1]
print(msg)

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('-------------')

    user = discord.User(id = '354240853071364097')
    
    await client.send_message(user, msg)
    await client.logout() # logging out ends the event loop
    return None


with open(sys.path[0] + '/token', 'r') as tokenfile:
    token = tokenfile.read().replace("\n", "")
    client.run(token)

