#!/bin/sh

# if word MARWIP found in repo, do not push

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		# Check for WIP message
		MARWIP_CODE=`git grep -n 'MARWIP'`
		MARWIP_COMMIT=`git log --all --grep='MARWIP'`
		MARDEV_CODE=`git grep -n 'MARDEV'`
		MARDEV_COMMIT=`git log --all --grep='MARDEV'`
        CONCAT="$MARWIP_CODE
        $MARWIP_COMMIT
        $MARDEV_CODE
        $MARDEV_COMMIT"
        CONCAT_NS=$(echo $CONCAT | sed '/^[[:space:]]*$/d')

		if [[ "$CONCAT_NS" = *[![:blank:]]* ]]
		then
			echo "Found word MARWIP or MARDEV in code or commit, not pushing"
            echo ==============
            for match in "$CONCAT"
            do
                echo "$match"
            done
            echo ==============
			exit 1
		fi

	fi
done

exit 0
