#!/bin/sh

# if word MARWIP found in repo, do not push

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		# Check for WIP message
		MARWIP=`git grep -n 'MARWIP'`
        # echo $MARWIP
		# exit 1
		if [ -n "$MARWIP" ]
		then
			echo "Found word MARWIP in repo, not pushing"
            for match in "$MARWIP"
            do
                echo - $match
            done
			exit 1
		fi
	fi
done

exit 0
