#!/usr/bin/env bash

URL=http://localhost
REALM=somerealm
CLIENT_ID=clientid
SECRET=987ca5d3-276f-4803-b41c-7c79106ceac2

# if using proxy, like traefik, then must tell curl which host is targeting. URL is then http://localhost.

curl -H "host: oauth.localhost" --location --request POST "$URL/auth/realms/$REALM/protocol/openid-connect/token" \
--header "Content-Type: application/x-www-form-urlencoded" \
--data-urlencode "client_id=$CLIENT_ID" \
--data-urlencode "client_secret=$SECRET" \
--data-urlencode "grant_type=client_credentials" | jq '.["access_token"]' | tail -c +2 | head -c -2

