#!/usr/bin/env bash

curl --location --request POST 'http://devdlapdvhq1.int.lessor.dk:8180/auth/realms/danlon/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=CLIENT_ID' \
--data-urlencode 'client_secret=SECRET' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=USERNAME' \
--data-urlencode 'password=PASSWORD' | jq '.["access_token"]' | tail -c +2 | head -c -2 | clip.exe


