#!/usr/bin/env bash

TENANT=<TenantId>
CLIENT_ID=<ClientId>
SECRET=<ClientSecret>

curl --location --request POST "https://login.microsoftonline.com/$TENANT/oauth2/token" \
--header "Content-Type: application/x-www-form-urlencoded" \
--data-urlencode "client_id=$CLIENT_ID" \
--data-urlencode "client_secret=$SECRET" \
--data-urlencode "grant_type=client_credentials" \
| jq '.["access_token"]' | tail -c +2 | head -c -2

# if you want to use scope parameter then url end should be: /oauth2/v2.0/token
# --data-urlencode "scope=openid email" \

# if you want id_token, add scope=openid to form params
### eg: --data-urlencode "scope=openid" \

