version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./test.html:/usr/share/nginx/html/test.html
        ports:
            - 80:80
